Added more functionality
Added support for local environments
Added usage messages
Added support for different project and exercise directories

diff --git a/complexitystats b/complexitystats
--- a/complexitystats
+++ b/complexitystats
@@ -1,40 +1,65 @@
 #!/bin/bash
-set -e
-ASGN=$1
-cd $DIR357
-if [ ! -d $ASGN ]; then
-   echo "Invalid assignment: $ASGN"
-   exit 2
+if [[ $# == 0 ]]; then
+   echo "Usage: "
+   echo "   $0 <ASGN_NAME>"
+   echo
+   echo "<ASGN_NAME> can be in any of the following formats:"
+   echo "      #           Ex. $0 1 (calls Exercise1)"
+   echo "      P#          Ex. $0 P1 (calls Project1)"
+   echo "      Exercise#   Ex. $0 Exercise1"
+   echo "      Project#    Ex. $0 Project1"
+   exit 1
 fi
-cd $ASGN
-complexity -t0 -s1 *.c > complexity$ASGN
-re='^[0-9]+$'
-NUM=0
-VALS=( )
-SUM=0
-MAX=0
-while read -r line; do
-   set -- $line
-   if [[ $1 =~ $re ]]; then
-      VALS[$NUM]=$1
-      CUR=$1
-      NUM=$((NUM+1))
-      SUM=$((SUM+CUR))
-      if [ $1 -gt $MAX ]; then
-         MAX=$1
-      fi
+if [ -n "$SSH_CLIENT" ] ; then 
+   set -e
+   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+   cd "$CURDIR"
+   . ./getasgn $1
+   cd "$REMOTEASGNDIR"
+   if [ ! -d $ASGN ]; then
+      echo "Invalid assignment: $ASGN"
+      exit 2
    fi
-done < complexity$ASGN
-((AVG=SUM/NUM))
-Q4=$((NUM/4))
-Q4SUM=0
-i=0
-for (( i = NUM-Q4; i < NUM; i++ )); do
-   CUR=${VALS[$i]}
-   Q4SUM=$((Q4SUM+CUR))
-done
-Q4R=$(echo "$Q4SUM / $SUM" | bc -l)
-echo "TOT: $SUM"
-echo "AVG: $AVG"
-echo "MAX: $MAX"
-echo "Q4R: $Q4R"
+   cd $ASGN
+   complexity -t0 -s1 *.c > complexity$ASGN
+   re='^[0-9]+$'
+   NUM=0
+   VALS=( )
+   SUM=0
+   MAX=0
+   while read -r line; do
+      set -- $line
+      if [[ $1 =~ $re ]]; then
+         VALS[$NUM]=$1
+         CUR=$1
+         NUM=$((NUM+1))
+         SUM=$((SUM+CUR))
+         if [ $1 -gt $MAX ]; then
+            MAX=$1
+         fi
+      fi
+   done < complexity$ASGN
+   ((AVG=SUM/NUM))
+   Q4=$((NUM/4))
+   Q4SUM=0
+   i=0
+   for (( i = NUM-Q4; i < NUM; i++ )); do
+      CUR=${VALS[$i]}
+      Q4SUM=$((Q4SUM+CUR))
+   done
+   Q4R=$(echo "$Q4SUM / $SUM" | bc -l)
+   echo "TOT: $SUM"
+   echo "AVG: $AVG"
+   echo "MAX: $MAX"
+   echo "Q4R: $Q4R"
+
+else
+   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+   cd "$CURDIR"
+   . ./getasgn $1
+   cd "$ASGNDIR"
+   rsync -av $ASGN/* "$CPUSER@unix$UNIX.csc.calpoly.edu:/$REMOTEASGNDIR/$ASGN" > /dev/null
+   ssh $CPUSER@unix$UNIX.csc.calpoly.edu -t "$REMOTEDIR/calccomplexity $1"
+fi
+
+
diff --git a/newtest b/newtest
--- a/newtest
+++ b/newtest
@@ -1,64 +1,83 @@
 #!/bin/bash
-set -e
-ASGN=$1
-source PATHS
-cd $DIR357
-cd $ASGN
-make clean
-make
-NUM=1
-FILE="in$NUM"
-while [ -e "$FILE" ]; do
-   NUM=$((NUM+1))
+if [[ $# == 0 ]]; then
+   echo "Usage: "
+   echo "   $0 <ASGN_NAME>"
+   echo
+   echo "<ASGN_NAME> can be in any of the following formats:"
+   echo "      #           Ex. $0 1 (calls Exercise1)"
+   echo "      P#          Ex. $0 P1 (calls Project1)"
+   echo "      Exercise#   Ex. $0 Exercise1"
+   echo "      Project#    Ex. $0 Project1"
+   exit 1
+fi
+if [ -n "$SSH_CLIENT" ] ; then 
+   set -e
+   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+   cd "$CURDIR"
+   . ./getasgn $1
+   cd "$REMOTEASGNDIR"
+   cd $ASGN
+   make clean
+   make
+   NUM=1
    FILE="in$NUM"
-done
-
-echo "Command line args?"
-read ARGS
-
-echo "Writing to $FILE! Type quit to finish"
-echo $ARGS > $FILE
-
-while read line && [ "$line" != "quit" ]; do
-   echo $line >> $FILE
-done
-echo "Running your code..."
-set +e
-tail -n +2 $FILE | ./a.out `head -1 $FILE` > $FILE.myout 2> $FILE.myerr
-
-#Inst
-echo "Running instructor code..."
-DIR="/home/kmammen/357/$ASGN"
-if [ ! -d $DIR ]; then
-   echo "$ASGN not found!"
-   exit
-fi
-cd $DIR
-NUM=0
-FILES=( )
-for f in *; do
-   if [ -f "$f" ] && [ -x "$f" ]; then
-      FILES[$NUM]=$f
+   while [ -e "$FILE" ]; do
       NUM=$((NUM+1))
-   fi
-done
-INST=0
-if [[ $NUM == 0 ]]; then
-   echo "No executable found!"
-   exit
-fi
-if [[ $NUM > 1 ]]; then
-   echo "Multiple executables found!"
-   for (( i = 0; i < $NUM; i++ )); do
-      echo "$i: ${FILES[$i]}"
+      FILE="in$NUM"
    done
-   echo "Which one? "
-   read INST
+
+   echo "Command line args?"
+   read ARGS
+   
+   echo "Writing to $FILE! Type quit to finish"
+   echo $ARGS > $FILE
+
+   while read line && [ "$line" != "quit" ]; do
+      echo $line >> $FILE
+   done
+   set +e
+   tail -n +2 $FILE | ./a.out `head -1 $FILE` > $FILE.myout 2> $FILE.myerr
+
+   #Inst
+   DIR="/home/kmammen/357/$ASGN"
+   if [ ! -d $DIR ]; then
+      echo "$ASGN not found!"
+      exit
+   fi
+   cd $DIR
+   NUM=0
+   FILES=( )
+   for f in *; do
+      if [ -f "$f" ] && [ -x "$f" ]; then
+         FILES[$NUM]=$f
+         NUM=$((NUM+1))
+      fi
+   done
+   INST=0
+   if [[ $NUM == 0 ]]; then
+      echo "No executable found!"
+      exit
+   fi
+   if [[ $NUM > 1 ]]; then
+      echo "Multiple executables found!"
+      for (( i = 0; i < $NUM; i++ )); do
+         echo "$i: ${FILES[$i]}"
+      done
+      echo "Which one? "
+      read INST
+   fi
+   cd $HOME/cpe357/$ASGN
+   tail -n +2 $FILE | $DIR/${FILES[$INST]} `head -1 $FILE` > $FILE.out 2> $FILE.err
+   echo
+   diff $FILE.out $FILE.myout
+   diff $FILE.err $FILE.myerr
+else
+   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+   cd "$CURDIR"
+   . ./getasgn $1
+   cd "$ASGNDIR"
+   rsync -av $ASGN/* "$CPUSER@unix$UNIX.csc.calpoly.edu:$REMOTEASGNDIR/$ASGN" > /dev/null
+   ssh $CPUSER@unix$UNIX.csc.calpoly.edu -t "$REMOTEDIR/newtest ${@:1}"
+   rsync -av $CPUSER@unix$UNIX.csc.calpoly.edu:$REMOTEASGNDIR/$ASGN/in* $ASGN > /dev/null
 fi
-cd $HOME/cpe357/$ASGN
-tail -n +2 $FILE | $DIR/${FILES[$INST]} `head -1 $FILE` > $FILE.out 2> $FILE.err
-echo "Diffing output..."
-diff $FILE.out $FILE.myout
-diff $FILE.err $FILE.myerr
-echo "Done!"
 
diff --git a/requirements b/requirements
--- a/requirements
+++ b/requirements
@@ -1,42 +1,67 @@
 #!/bin/bash
-ASGN=$1
-source PATHS
-DIR="/home/kmammen-grader/evaluations/W17/357/$ASGN"
-if [ ! -d $DIR ]; then
-   echo "Invalid assignment: $ASGN"
-   exit 2
+if [[ $# == 0 ]]; then
+   echo "Usage: "
+   echo "   $0 <ASGN_NAME>"
+   echo
+   echo "<ASGN_NAME> can be in any of the following formats:"
+   echo "      #           Ex. $0 1 (calls Exercise1)"
+   echo "      P#          Ex. $0 P1 (calls Project1)"
+   echo "      Exercise#   Ex. $0 Exercise1"
+   echo "      Project#    Ex. $0 Project1"
+   exit 1
 fi
-if [ ! -r $DIR/requirements ]; then
-   echo "$ASGN is not available yet!"
-   exit 1;
-fi
-cd $DIR357
-if [ ! -d $ASGN ]; then
-   mkdir $ASGN
-   cp "$DIR/Makefile" "$ASGN"
-fi
+if [ -n "$SSH_CLIENT" ] ; then 
+   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+   cd "$CURDIR"
+   . ./getasgn $1
+   cd "$REMOTEASGNDIR"
+   DIR="/home/kmammen-grader/evaluations/W17/357/$ASGN"
+   if [ ! -d $DIR ]; then
+      echo "Invalid assignment: $ASGN"
+      exit 2
+   fi
+   if [ ! -r $DIR/requirements ]; then
+      echo "$ASGN is not available yet!"
+      exit 1;
+   fi
+   cd $HOME/cpe357
+   if [ ! -d $ASGN ]; then
+      mkdir $ASGN
+      cp "$DIR/Makefile" "$ASGN"
+   fi
 
-echo "REQUIREMENTS"
-cat "$DIR/requirements"
-if [ -d $DIR/tests/core ]; then
-   echo
-   echo "CORE"
-   cd $DIR/tests/core
-   for f in *; do
-      if [ -d ${f} ]; then
-         # Will not run if no directories are available
-         cat $f/description
-      fi
-   done
-fi
-if [ -d $DIR/tests/feature ]; then
-   echo
-   echo "FEATURE"
-   cd $DIR/tests/feature
-   for f in *; do
-      if [ -d ${f} ]; then
-         # Will not run if no directories are available
-         cat $f/description
-      fi
-   done
+   echo "REQUIREMENTS"
+   cat "$DIR/requirements"
+   if [ -d $DIR/tests/core ]; then
+      echo
+      echo "CORE"
+      cd $DIR/tests/core
+      for f in *; do
+         if [ -d ${f} ]; then
+            # Will not run if no directories are available
+            cat $f/description
+         fi
+      done
+   fi
+   if [ -d $DIR/tests/feature ]; then
+      echo
+      echo "FEATURE"
+      cd $DIR/tests/feature
+      for f in *; do
+         if [ -d ${f} ]; then
+            # Will not run if no directories are available
+            cat $f/description
+         fi
+      done
+   fi
+else
+   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+   cd "$CURDIR"
+   . ./getasgn $1
+   cd "$ASGNDIR"
+   ssh $CPUSER@unix$UNIX.csc.calpoly.edu -t "$REMOTEASGNDIR/requirements $1"
+   if (ssh $CPUSER@unix$UNIX.csc.calpoly.edu "[ -d $REMOTEASGNDIR/$ASGN ]"); then
+      mkdir $ASGN
+      rsync -av $CPUSER@unix$UNIX.csc.calpoly.edu:$REMOTEASGNDIR/$ASGN/* $ASGN > /dev/null
+   fi
 fi
diff --git a/run b/run
--- a/run
+++ b/run
@@ -1,12 +1,38 @@
 #!/bin/bash
-set -e
-ASGN=$1
-cd $DIR357
-if [ ! -d $ASGN ]; then
-   echo "Invalid assignment: $ASGN"
-   exit 2
+if [[ $# == 0 ]]; then
+   echo "Usage: "
+   echo "   $0 <ASGN_NAME>"
+   echo
+   echo "<ASGN_NAME> can be in any of the following formats:"
+   echo "      #           Ex. $0 1 (calls Exercise1)"
+   echo "      P#          Ex. $0 P1 (calls Project1)"
+   echo "      Exercise#   Ex. $0 Exercise1"
+   echo "      Project#    Ex. $0 Project1"
+   exit 1
 fi
-cd $ASGN
-make clean
-make
-./a.out ${@:2}
+if [ -n "$SSH_CLIENT" ] ; then 
+   set -e
+   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+   cd "$REMOTECURDIR"
+   . ./getasgn $1
+   cd "$ASGNDIR"
+   if [ ! -d $ASGN ]; then
+      echo "Invalid assignment: $ASGN"
+      exit 2
+   fi
+   cd $ASGN
+   make clean
+   make
+   echo "Program Output:"
+   echo
+   ./a.out ${@:2}
+   echo
+else
+   CURDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+   cd "$CURDIR"
+   . ./getasgn $1
+   cd "$ASGNDIR"
+   rsync -av $ASGN/* "$CPUSER@unix$UNIX.csc.calpoly.edu:$REMOTEASGNDIR/$ASGN" > /dev/null
+   ssh $CPUSER@unix$UNIX.csc.calpoly.edu -t "$REMOTEDIR/run ${@:1}"
+fi
+
